version: 2

models:
  # Dimension Tables
  - name: dim_users
    description: "User dimension with enriched attributes and segmentation"
    columns:
      - name: user_id
        description: "Primary key"
        tests:
          - unique
          - not_null

  - name: dim_date
    description: "Date dimension for time-based analysis"
    columns:
      - name: date_key
        description: "Primary key (YYYYMMDD)"
        tests:
          - unique
          - not_null

  - name: dim_plan
    description: "Subscription plan dimension"
    columns:
      - name: plan_key
        description: "Primary key"
        tests:
          - unique
          - not_null

  - name: dim_channel
    description: "Acquisition channel dimension"
    columns:
      - name: channel_key
        description: "Primary key"
        tests:
          - unique
          - not_null

  # Fact Tables
  - name: fct_events
    description: "Event facts for user interaction analysis"
    columns:
      - name: event_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Foreign key to dim_users"
        tests:
          - not_null
          - relationships:
              to: ref('dim_users')
              field: user_id

  - name: fct_sessions
    description: "Session facts for engagement analysis"
    columns:
      - name: session_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Foreign key to dim_users"
        tests:
          - not_null
          - relationships:
              to: ref('dim_users')
              field: user_id

  - name: fct_subscriptions
    description: "Subscription facts for revenue and churn analysis"
    columns:
      - name: subscription_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Foreign key to dim_users"
        tests:
          - not_null
          - relationships:
              to: ref('dim_users')
              field: user_id

  - name: fct_payments
    description: "Payment facts for revenue and financial analysis"
    columns:
      - name: payment_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Foreign key to dim_users"
        tests:
          - not_null
          - relationships:
              to: ref('dim_users')
              field: user_id

  - name: fct_daily_metrics
    description: "Daily aggregated metrics for KPI tracking"
    columns:
      - name: date
        description: "Metric date"
        tests:
          - unique
          - not_null
      - name: daily_active_users
        description: "Count of unique active users"
      - name: new_signups
        description: "Count of new user signups"
